---
title: "5fC mouse sperm file preparation"
author: "Vincent Fischer"
date: "24 05 2023"
output:
html_document:
    toc: true
    toc_float: true
    theme: spacelab
    code_folding: hide
    fig_width: 12
    df_print: paged
    number_sections: true
    

---

# load packages
```{r}
suppressPackageStartupMessages({
  library(R.utils)
  library(liftOver)
  library(GenomicRanges)
  })
```
# unzip files
unzip (untar) tar file with bed files, unzip (gunzip)
```{r, eval=TRUE}
untar("../object_resources/5fC/GSE84833_RAW.tar",exdir = "../object_resources/5fC/")
m_sp_5fC_list <- list.files("../object_resources/5fC/",pattern = ".bed.gz$", full.names = TRUE)# listed zip files
m_sp_5fC_list
for(i in c(1:length(m_sp_5fC_list))){
  gunzip(m_sp_5fC_list[i])
} #zip files are deleted in the process
```

# list bed files
```{r, eval=TRUE}
m_sp_5fC_bedlist <- list.files("../object_resources/5fC/", pattern = ".bed$", full.names = TRUE)# list bed files
m_sp_5fC <- lapply(X = m_sp_5fC_bedlist, FUN = import)
for(i in c(1:length(m_sp_5fC))){
 print(table((m_sp_5fC[[i]]$score)))
} 

```

# import chain for liftOver
```{r}
mm9tomm10_chain <- import.chain("../object_resources/mm9ToMm10.over.chain")
```


# liftover for all samples
```{r}
mm9_mm10_5fC_sp <- lapply(m_sp_5fC,FUN = liftOver, chain =mm9tomm10_chain)
mm9_mm10_5fC_sp_unlisted_per_sample <- lapply(mm9_mm10_5fC_sp,unlist)

for(i in c(1:length(mm9_mm10_5fC_sp_unlisted_per_sample))){
 print(table((mm9_mm10_5fC_sp_unlisted_per_sample[[i]]$score)))
} 

mm9_mm10_5fC_sp_unlisted_in_total <- unlist(GRangesList(mm9_mm10_5fC_sp_unlisted_per_sample))

# save 5fC sites in mm10
saveRDS(mm9_mm10_5fC_sp_unlisted_in_total,"../object_resources/5fC/merged_5fC_sp_mm9tomm10.rds")


```

# prepare 5fC and no5fC sites
```{r}
total_5fC_lit <- readRDS("../object_resources/5fC/merged_5fC_sp_mm9tomm10.rds")
seqlevelsStyle(total_5fC_lit)<-"Ensembl" 
sites_5fC  <- reduce(total_5fC_lit[total_5fC_lit$score==1])
sites_5fC <-keepStandardChromosomes(x = sites_5fC,pruning.mode = "coarse")

saveRDS(sites_5fC,"../object_resources/5fC/sites_5fC.rds")

sites_no5fC <- reduce(total_5fC_lit[total_5fC_lit$score==0]) 
# remove no5fC site in proximity to 5fC sites (2kb)
sites_no5fC <- sites_no5fC[!overlapsAny(sites_no5fC,sites_5fC,type = "any", maxgap = 2000)]
# remove no5fC sites in proximity to other no5fC sites (2kb)
sites_no5fC <- reduce(resize(sites_no5fC,fix = "center", width = 2000))
# resizing no5fC sites to there actual location
sites_no5fC <- resize(sites_no5fC, fix = "center", width = 0)

sites_no5fC <-keepStandardChromosomes(x = sites_no5fC,pruning.mode = "coarse")

saveRDS(sites_no5fC,"../object_resources/5fC/sites_no5fC.rds")
```


# SessionInfo
```{r}
sessionInfo()
```

