---
title: "TSS_preparation"
author: "Vincent Fischer"
date: "24 5 2023"
output: 
    html_document:
      toc: true
      toc_float: true
      theme: spacelab
      code_folding: hide
      fig_width: 12
      df_print: paged
      number_sections: true
    

---

# load packages
```{r}
suppressPackageStartupMessages({
library(AnnotationHub)
library(knitr)  
library(GenomicRanges)
  })
```
# load 5fC and no5fC site object
unzip (untar) tar file with bed files, unzip (gunzip)
```{r, eval=TRUE}
sites_5fC <-readRDS("../object_resources/5fC/sites_5fC.rds")
sites_no5fC <- readRDS("../object_resources/5fC/sites_no5fC.rds")
```

# load TSS
```{r}

ah <- AnnotationHub()
#display(ah)

# load annotation
ensdb <- ah[["AH89211"]] #GRCm38 V102
seqlevelsStyle(ensdb)
```

```{r}
# extract TSS from Annotation
tss <- GenomicRanges::promoters(ensdb,upstream = 2000,downstream = 2000)
seqlevelsStyle(tss)

```

# extract TSS with and without 5fC
```{r}
# check for overlaps of TSS with 5fC reduce to remove getting the tss twice
TSS_2KB_5fC <- reduce(tss[overlapsAny(tss,sites_5fC)])
TSS_2KB_no5fC <- reduce(tss[overlapsAny(tss,sites_no5fC)])
# remove no5fC TSS sites which are also labelled as 5fC TSS sites
TSS_2KB_no5fC <- TSS_2KB_no5fC[!overlapsAny(TSS_2KB_no5fC,TSS_2KB_5fC)]


saveRDS(TSS_2KB_5fC,"../object_resources/5fC/TSS_2KB_5fC.rds")
saveRDS(TSS_2KB_no5fC,"../object_resources/5fC/TSS_2KB_no5fC.rds")
```



# extract 5fC and no5fC sites in proximity to a TSS
5fC sites in close proximity to a TSS (+-2KB)
```{r}
unique_5fC_sites_in_TSS <- sites_5fC[overlapsAny(sites_5fC,tss)]
# make sure no other 5fC sites are in proximity
unique_5fC_sites_in_TSS <- reduce(resize(unique_5fC_sites_in_TSS,fix = "center",width = 2000))

saveRDS(unique_5fC_sites_in_TSS,"../object_resources/5fC/unique_5fC_sites_in_TSS.rds")

```

no5fC sites in close proximity to a TSS (+-2KB)
```{r}
unique_no5fC_sites_in_TSS <- sites_no5fC[overlapsAny(sites_no5fC,tss)]

# make sure no other no5fC sites are in proximity
unique_no5fC_sites_in_TSS <- reduce(resize(unique_no5fC_sites_in_TSS,fix = "center",width = 2000))
saveRDS(unique_no5fC_sites_in_TSS,"../object_resources/5fC/unique_no5fC_sites_in_TSS.rds")
```


# SessionInfo
```{r}
sessionInfo()
```